import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-dvh md:min-h-screen md:bg-gray-200 md:flex md:items-center md:justify-center md:p-4 md:p-8">
          <div className="w-full md:max-w-[428px] bg-white min-h-dvh md:min-h-[926px] md:rounded-[2.5rem] md:shadow-2xl md:overflow-hidden relative">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
