import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="min-h-dvh">
          <header className="border-b">
            <div className="max-w-5xl mx-auto flex items-center justify-between p-4">
              <a href="/" className="font-semibold">Sports Booking</a>
              <nav className="text-sm space-x-4">
                <a href="/search">Search</a>
                <a href="/owner">Owner</a>
                <a href="/admin">Admin</a>
                <a href="/login">Login</a>
              </nav>
            </div>
          </header>
          <main className="max-w-5xl mx-auto p-4">{children}</main>
        </div>
      </body>
    </html>
  );
}
