-- =============================================================================
-- CSC Pickleball — insert 144 participants (one tournament, all categories)
-- =============================================================================
-- Run AFTER creating the tournament (individual mode, sport: pickleball).
-- Replace fab66efc-f0da-4d4a-a9f3-42cad5fb1f09 with your tournament UUID.
--
-- Alternative: upload db/csc_pickleball_participants.csv from the Participants tab.
-- =============================================================================

BEGIN;

WITH p AS (
  SELECT 'fab66efc-f0da-4d4a-a9f3-42cad5fb1f09'::uuid AS tournament_id
),
wanted AS (
  SELECT * FROM (VALUES
    ('Aashi Mour', 'Mixed Doubles', 'Mixed Doubles · Group B'),
    ('Aba Parab', 'Mens Doubles', 'Mens Doubles · Group H'),
    ('Aditya Seth', 'Mens Doubles', 'Mens Doubles · Group H'),
    ('Ajay Soni', 'Mens Doubles', 'Mens Doubles · Group C'),
    ('Akash Bajaj', 'Mens Doubles', 'Mens Doubles · Group L'),
    ('Akshan Agrawal', 'Mixed Doubles', 'Mixed Doubles · Group C'),
    ('Akshay Amin', 'Mens Doubles | Mixed Doubles', NULL),
    ('Akshay Jagani', 'Mixed Doubles', 'Mixed Doubles · Group C'),
    ('Alessan Agrawal', 'Mens Doubles', 'Mens Doubles · Group G'),
    ('Aleta Almeida', 'Mixed Doubles', 'Mixed Doubles · Group A'),
    ('Anand Jain', 'Mens Doubles', 'Mens Doubles · Group M'),
    ('Anish Jalui', 'Mens Doubles', 'Mens Doubles · Group I'),
    ('Ankit Rathi', 'Mens Doubles', 'Mens Doubles · Group M'),
    ('Arag Daga', 'Mens Doubles | Mixed Doubles', NULL),
    ('Archana Kumawat', 'Females Doubles | Mixed Doubles', NULL),
    ('Aryan Pawar', 'Mens Doubles', 'Mens Doubles · Group A'),
    ('Ashok Biyani', 'Mens Doubles', 'Mens Doubles · Group G'),
    ('Asmita Jain', 'Females Doubles', 'Females Doubles · Group A'),
    ('Ayush Shah', 'Mens Doubles', 'Mens Doubles · Group J'),
    ('Babita', 'Mixed Doubles', 'Mixed Doubles · Group A'),
    ('Babita Rana', 'Females Doubles', 'Females Doubles · Group A'),
    ('Bhavuk Singhal', 'Mens Doubles', 'Mens Doubles · Group H'),
    ('CA Ashish Mishra', 'Mixed Doubles', 'Mixed Doubles · Group B'),
    ('CA Divyang Kothari', 'Mens Doubles', 'Mens Doubles · Group L'),
    ('CA Karan Parmar', 'Mens Doubles', 'Mens Doubles · Group L'),
    ('CA Neeraj Mishra', 'Mens Doubles', 'Mens Doubles · Group J'),
    ('Darryl Gonsalves', 'Mens Doubles', 'Mens Doubles · Group L'),
    ('Deepak Bothra', 'Mens Doubles', 'Mens Doubles · Group I'),
    ('Deepali Bardia', 'Females Doubles | Mixed Doubles', NULL),
    ('Dharmi Nandu', 'Females Doubles', 'Females Doubles · Group B'),
    ('Dviti Shah', 'Mixed Doubles', 'Mixed Doubles · Group A'),
    ('Esha Dedavat', 'Females Doubles | Mixed Doubles', NULL),
    ('Ganesh Koshti', 'Mens Doubles', 'Mens Doubles · Group J'),
    ('Giriraj Jadeja', 'Mens Doubles', 'Mens Doubles · Group I'),
    ('Govind Parashar', 'Mens Doubles', 'Mens Doubles · Group B'),
    ('Hardik Chotalia', 'Mens Doubles | Mixed Doubles', NULL),
    ('Harsh Dargar', 'Mens Doubles', 'Mens Doubles · Group E'),
    ('Harsh Kansara', 'Mens Doubles', 'Mens Doubles · Group A'),
    ('Harshil Shah', 'Mens Doubles', 'Mens Doubles · Group G'),
    ('Harshit Kalla', 'Mens Doubles | Mixed Doubles', NULL),
    ('Harshit Makwana', 'Mens Doubles', 'Mens Doubles · Group F'),
    ('Harshit Sethi', 'Mens Doubles | Mixed Doubles', NULL),
    ('Harshita Kalla', 'Mixed Doubles', 'Mixed Doubles · Group C'),
    ('Hassan Khatri', 'Mens Doubles', 'Mens Doubles · Group J'),
    ('Hiral Nandu', 'Females Doubles', 'Females Doubles · Group B'),
    ('Jayant Mehra', 'Mens Doubles', 'Mens Doubles · Group D'),
    ('Kamal A', 'Mens Doubles', 'Mens Doubles · Group A'),
    ('Kamal Agarwal', 'Mens Doubles', 'Mens Doubles · Group I'),
    ('Kapil Goyal', 'Mens Doubles', 'Mens Doubles · Group D'),
    ('Karthik', 'Mens Doubles', 'Mens Doubles · Group I'),
    ('Kartik Meridatta', 'Mixed Doubles', 'Mixed Doubles · Group A'),
    ('Kartik Ramesh Ladha', 'Mens Doubles', 'Mens Doubles · Group K'),
    ('Kartil Jain', 'Mens Doubles', 'Mens Doubles · Group M'),
    ('Kenali Shah', 'Females Doubles | Mixed Doubles', NULL),
    ('Ketan Patil', 'Mens Doubles', 'Mens Doubles · Group C'),
    ('Kinjal Chotalia', 'Mixed Doubles', 'Mixed Doubles · Group D'),
    ('Krish Agarwal', 'Mens Doubles', 'Mens Doubles · Group A'),
    ('Krupa Sanghavi', 'Females Doubles', 'Females Doubles · Group B'),
    ('Krushabh Naik', 'Mens Doubles', 'Mens Doubles · Group D'),
    ('Kunal Modi', 'Mens Doubles', 'Mens Doubles · Group G'),
    ('Lance', 'Mens Doubles', 'Mens Doubles · Group F'),
    ('Maitri Hemant Vikam', 'Females Doubles | Mixed Doubles', NULL),
    ('Manan Shah', 'Mixed Doubles', 'Mixed Doubles · Group A'),
    ('Mayank Bajaj', 'Mens Doubles', 'Mens Doubles · Group L'),
    ('Mayur Mundhra', 'Mens Doubles', 'Mens Doubles · Group H'),
    ('Mayur Tank', 'Mens Doubles', 'Mens Doubles · Group C'),
    ('Mehul Bhastana', 'Mens Doubles', 'Mens Doubles · Group B'),
    ('Mehul Patel', 'Mens Doubles', 'Mens Doubles · Group C'),
    ('Mitesh Raja', 'Mens Doubles', 'Mens Doubles · Group I'),
    ('Mohak Ishwar', 'Mens Doubles', 'Mens Doubles · Group M'),
    ('Mohit Chothwani', 'Mens Doubles', 'Mens Doubles · Group G'),
    ('Monica Pandya', 'Females Doubles', 'Females Doubles · Group A'),
    ('Morris Lopes', 'Mens Doubles | Mixed Doubles', NULL),
    ('Mudrank Jain', 'Mens Doubles', 'Mens Doubles · Group M'),
    ('Munket Soni', 'Mens Doubles', 'Mens Doubles · Group C'),
    ('Navneet Upadhyay', 'Mens Doubles', 'Mens Doubles · Group D'),
    ('Nayan', 'Mens Doubles', 'Mens Doubles · Group I'),
    ('Neeraj Mishra', 'Mens Doubles', 'Mens Doubles · Group B'),
    ('Neeraj Surendra Jaiswal', 'Mens Doubles | Mixed Doubles', NULL),
    ('Nidhi Maskare', 'Females Doubles', 'Females Doubles · Group A'),
    ('Nikhil Agarwal', 'Mens Doubles', 'Mens Doubles · Group B'),
    ('Nivesh Beria', 'Mens Doubles', 'Mens Doubles · Group G'),
    ('Niyati Fofadia', 'Females Doubles', 'Females Doubles · Group A'),
    ('Palak', 'Mens Doubles', 'Mens Doubles · Group M'),
    ('Parth Shrimankar', 'Mens Doubles', 'Mens Doubles · Group C'),
    ('Parth Thathagar', 'Mens Doubles', 'Mens Doubles · Group G'),
    ('Parul Gupta', 'Females Doubles | Mixed Doubles', NULL),
    ('Piyush Laddha', 'Mens Doubles', 'Mens Doubles · Group B'),
    ('Pooja Patekar', 'Females Doubles', 'Females Doubles · Group A'),
    ('Pratik Shinde', 'Mens Doubles', 'Mens Doubles · Group K'),
    ('Pratik Solanki', 'Mens Doubles', 'Mens Doubles · Group A'),
    ('Pravesh Jain', 'Mens Doubles', 'Mens Doubles · Group H'),
    ('Pravin Thanvi', 'Mens Doubles', 'Mens Doubles · Group G'),
    ('Prerit Jain', 'Mens Doubles', 'Mens Doubles · Group B'),
    ('Prerit Mehta', 'Mixed Doubles', 'Mixed Doubles · Group B'),
    ('Prithviraj Todi', 'Mens Doubles', 'Mens Doubles · Group E'),
    ('Priya Gupta', 'Mixed Doubles', 'Mixed Doubles · Group C'),
    ('Puneet Trivedi', 'Mens Doubles', 'Mens Doubles · Group D'),
    ('Rahul Bhuva', 'Mens Doubles | Mixed Doubles', NULL),
    ('Rajan Tiwari', 'Mens Doubles', 'Mens Doubles · Group C'),
    ('Rakshita', 'Mixed Doubles', 'Mixed Doubles · Group B'),
    ('Ram Goenka', 'Mens Doubles', 'Mens Doubles · Group F'),
    ('Ramesh Jain', 'Mens Doubles', 'Mens Doubles · Group E'),
    ('Rishabh Parekh', 'Mens Doubles | Mixed Doubles', NULL),
    ('Rocky Patil', 'Mens Doubles', 'Mens Doubles · Group K'),
    ('Rohit Jain', 'Mens Doubles', 'Mens Doubles · Group F'),
    ('Rohit Nagarkar', 'Mens Doubles', 'Mens Doubles · Group J'),
    ('Rohit Ningoo', 'Mens Doubles', 'Mens Doubles · Group K'),
    ('Ronak Agarwal', 'Mens Doubles', 'Mens Doubles · Group K'),
    ('Ronak Osthwal', 'Mens Doubles', 'Mens Doubles · Group J'),
    ('Ruchita', 'Females Doubles', 'Females Doubles · Group B'),
    ('Sagar Aswal', 'Mens Doubles | Mixed Doubles', NULL),
    ('Sagar Parikh', 'Mens Doubles', 'Mens Doubles · Group E'),
    ('Saksham Maheshwari', 'Mens Doubles', 'Mens Doubles · Group E'),
    ('Sakshi Chavan', 'Mixed Doubles', 'Mixed Doubles · Group C'),
    ('Sakshi Jaiswal', 'Mixed Doubles', 'Mixed Doubles · Group C'),
    ('Sandya Pujari', 'Females Doubles', 'Females Doubles · Group A'),
    ('Sanyam Jain', 'Mens Doubles', 'Mens Doubles · Group K'),
    ('Shilpa Poojari', 'Mixed Doubles', 'Mixed Doubles · Group A'),
    ('Shonak Gupta', 'Mens Doubles', 'Mens Doubles · Group D'),
    ('Shreyans Kothari', 'Mens Doubles', 'Mens Doubles · Group A'),
    ('Siddharth Kyal', 'Mens Doubles', 'Mens Doubles · Group J'),
    ('Smeet Parikh', 'Mens Doubles', 'Mens Doubles · Group E'),
    ('Srikant Amarjeet Singh', 'Mens Doubles', 'Mens Doubles · Group B'),
    ('Sumit Bajaj', 'Mens Doubles', 'Mens Doubles · Group M'),
    ('Sumit Sharma', 'Mens Doubles | Mixed Doubles', NULL),
    ('Tanishk', 'Mens Doubles', 'Mens Doubles · Group E'),
    ('Tarun Kothari', 'Mens Doubles', 'Mens Doubles · Group D'),
    ('Taruna', 'Mixed Doubles', 'Mixed Doubles · Group D'),
    ('Taruna Vaishnav', 'Females Doubles', 'Females Doubles · Group B'),
    ('Theertha', 'Mixed Doubles', 'Mixed Doubles · Group D'),
    ('Theertha Cp', 'Females Doubles', 'Females Doubles · Group B'),
    ('Urvi Mota', 'Females Doubles | Mixed Doubles', NULL),
    ('Vaibhav Shah', 'Mens Doubles | Mixed Doubles', NULL),
    ('Vedant Harikrishan Gupta', 'Mens Doubles', 'Mens Doubles · Group F'),
    ('Venil Mehta', 'Mens Doubles', 'Mens Doubles · Group F'),
    ('Vijay Ladha', 'Mens Doubles', 'Mens Doubles · Group F'),
    ('Vikas Gupta', 'Mens Doubles | Mixed Doubles', NULL),
    ('Vinit', 'Mens Doubles', 'Mens Doubles · Group M'),
    ('Vishal Joshi', 'Mens Doubles', 'Mens Doubles · Group H'),
    ('Yash Bansal', 'Mens Doubles', 'Mens Doubles · Group K'),
    ('Yash Chaplot', 'Mixed Doubles', 'Mixed Doubles · Group D'),
    ('Yash Choumal', 'Mens Doubles', 'Mens Doubles · Group J'),
    ('Zaid Khandwani', 'Mens Doubles', 'Mens Doubles · Group A')
  ) AS v(player_name, category, club)
),
ins AS (
  INSERT INTO public.tournament_participants (
    tournament_id, user_id, player_name, phone, email, category, seed_number, club, status
  )
  SELECT
    p.tournament_id,
    NULL::uuid,
    w.player_name,
    NULL,
    NULL,
    w.category,
    NULL,
    w.club,
    'registered'
  FROM p
  CROSS JOIN wanted w
  WHERE NOT EXISTS (
    SELECT 1 FROM public.tournament_participants tp
    WHERE tp.tournament_id = p.tournament_id
      AND lower(regexp_replace(btrim(tp.player_name), '[[:space:]]+', ' ', 'g'))
        = lower(regexp_replace(btrim(w.player_name), '[[:space:]]+', ' ', 'g'))
  )
  RETURNING id, player_name, category
)
SELECT count(*) AS participants_inserted FROM ins;

COMMIT;
